import 'package:cash_book/constants/strings.dart';
import 'package:get/get.dart';

class Translate implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Track Income & Expenses": "Track Income & Expenses",
          "Manage Your Business with Staff": "Manage Your Business with Staff",
          "Set-Up Multiple Businesses": "Set-Up Multiple Businesses",
          "Stay updated on your profits": "Stay updated on your profits",
          "Add team members and assign roles":
              "Add team members and assign roles",
          "Keep multiple business records on one app":
              "Keep multiple business records on one app",
          'Skip': 'Skip',
          'Done': 'Done',
          'New Book': 'New Book',
          'ADD BOOK': 'ADD BOOK',
          'Book Name': 'Book Name',
          'Add': 'Add',
          'Private': 'Private',
          'Public': 'Public',
          'Login To Your Account': 'Login To Your Account',
          kWelcomeTitle: kWelcomeTitle,
          kUsernameTitle: kUsernameTitle,
          kUsernameHint: kUsernameHint,
          kPhoneNumberTitle: kPhoneNumberTitle,
          kDontHaveAnAccountText: kDontHaveAnAccountText,
          'Log In': 'Log In',
          'Enter The 4-Digit Code You Received':
              'Enter The 4-Digit Code You Received',
          'Submit': 'Submit',
          'Not sure about your number? ': 'Not sure about your number? ',
          'Change it here': 'Change it here',
          'Send SMS': 'Send SMS',
          'Don\'t have an account? ': 'Don\'t have an account? ',
          kCreateAccountText: kCreateAccountText,
          'language': 'language',
          kSignUpSubtitle: kSignUpSubtitle,
          kConditionsText: kConditionsText,
          kPhoneNumberHint: kPhoneNumberHint,
          kContinueText: kContinueText,
          kResendCodeText: kResendCodeText,
          kBackButtonText: kBackButtonText,
        },
        'fa': {
          "Track Income & Expenses": "پیگیری درآمد و هزینه ها",
          "Manage Your Business with Staff":
              "کسب و کار خود را با کارکنان مدیریت کنید",
          "Set-Up Multiple Businesses": "Set-Up Multiple Businesses",
          "Stay updated on your profits": "از  سود دریافتی خود مطلع باشید",
          "Add team members and assign roles":
              "اعضای تیم را اضافه کنید و برای هرکس نقش تعیین کنید",
          "Keep multiple business records on one app":
              "چندین سوابق تجاری را در یک برنامه نگه دارید",
          'Skip': 'رد کردن',
          'Done': 'اتمام',
          'New Book': 'کتاب جدید',
          'ADD BOOK': 'افزودن کتاب',
          'Book Name': 'نام کتاب',
          'Add': 'افزودن',
          'Private': 'خصوصی',
          'Public': 'عمومی',
          'Login To Your Account': 'وارد حساب کاربری خود شوید',
          kWelcomeTitle: 'به کشبوک خوش آمدید',
          kUsernameTitle: 'نام کاربری:',
          kUsernameHint: 'نام کاربری خود را وارد کنید',
          kPhoneNumberTitle: 'شماره تلفن:',
          kPhoneNumberHint: 'شماره تلفن خود را وارد کنید',
          kDontHaveAnAccountText: 'حساب کاربری ندارم ',
          'Log In': 'ورود به حساب',
          'Enter The 4-Digit Code You Received':
              'کد 4 رقمی ارسال شده را وارد کنید',
          'Submit': 'ثبت',
          'Not sure about your number? ': 'شماره اشتباه وارد کردید؟  ',
          'Change it here': 'تغییر شماره',
          'Send SMS': 'ارسال پیامک',
          'Don\'t have an account? ': 'حساب کاربری ندارید؟  ',
          '+981234567890': '+۹۸۱۲۳۴۵۶۷۸۹۰',
          kCreateAccountText: 'ثبت نام',
          'language': 'زبان',
          kSignUpSubtitle: 'برای ثبت نام فیلد‌های خواسته شده را پر کنید',
          kConditionsText: 'با شرایط و مقررات موافقم',
          kContinueText: 'ادامه',
          kResendCodeText: 'ارسال مجدد',
          kBackButtonText: 'برگشت',
        },
      };
}
